#!/bin/sh
#

# check for important processes
runningprocs=$(ps -ef | egrep '(ffmpeg|mythcommflag|mythtranscode|skype|HandbrakeCLI)' | grep -v egrep | wc -l)
if [ $runningprocs != 0 ]
then
  logger -p local0.notice -t checkshutdownok NOT OK - $runningprocs important processes running
  exit 1
else 
  logger -p local0.notice -t checkshutdownok no important processes running
fi

#
# EOF
