#!/bin/sh
#

# check if anyone is logged in
if smbstatus -S | tail -n +4 | grep -q ^[a-z]
then
  shares=$(smbstatus -S | tail -n +4 | grep ^[a-z] | awk '{print $1}' | sort | uniq | perl -pe 's/\n/, /' | perl -pe 's/, $//')
  logger -p local0.notice -t checkshutdownok NOT OK - samba shares in use: $shares
  exit 1
else
  logger -p local0.notice -t checkshutdownok samba not in use
fi

#
# EOF
